import { pgEnum, pgTable, uuid, text, timestamp, bigint, jsonb } from 'drizzle-orm/pg-core'
import { sql } from 'drizzle-orm'

export const supplementStatusEnum = pgEnum('supplement_status', [
  'draft',
  'pending',
  'published',
  'rejected',
])

export const userSuppRelationEnum = pgEnum('user_supp_relation', [
  'added',
  'uses',
  'favorite',
  'submitted',
])

export const users = pgTable('users', {
  id: uuid('id').primaryKey().default(sql`gen_random_uuid()`),
  email: text('email').notNull().unique(),
  username: text('username').unique(),
  passwordHash: text('password_hash'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

export const admins = pgTable('admins', {
  userId: uuid('user_id')
    .primaryKey()
    .references(() => users.id, { onDelete: 'cascade' }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

export const supplements = pgTable('supplements', {
  id: bigint('id', { mode: 'number' }).primaryKey().default(sql`generated by default as identity`),
  name: text('name').notNull(),
  brand: text('brand'),
  form: text('form'),
  servingSize: text('serving_size'), // numeric in SQL; keep as text for simplicity here
  servingUnit: text('serving_unit'),
  perServing: jsonb('per_serving'),
  status: supplementStatusEnum('status').notNull().default('draft'),
  createdBy: uuid('created_by').references(() => users.id, { onDelete: 'set null' }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  reviewedBy: uuid('reviewed_by').references(() => users.id, { onDelete: 'set null' }),
  reviewedAt: timestamp('reviewed_at', { withTimezone: true }),
  reviewNotes: text('review_notes'),
})

export const userSupplements = pgTable('user_supplements', {
  id: bigint('id', { mode: 'number' }).primaryKey().default(sql`generated by default as identity`),
  userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  supplementId: bigint('supplement_id', { mode: 'number' })
    .notNull()
    .references(() => supplements.id, { onDelete: 'cascade' }),
  relation: userSuppRelationEnum('relation').notNull().default('added'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
})

export type User = typeof users.$inferSelect
export type NewUser = typeof users.$inferInsert
export type Admin = typeof admins.$inferSelect
